### ISSUE TITLE
Typescript types don't work out of the box

### ISSUE THREAD

**Issue by enyo** [leaonline/easy-speech#268]
After installing and importing the package, I get:

```
There are types at '.../node_modules/easy-speech/dist/index.d.ts', but this result could not be resolved when respecting package.json "exports". The 'easy-speech' library may need to update its package.json or typings.
```

I'm not entirely sure, but I think changing the `exports` field to this should work:

```json
"exports": {
  ".": {
    "import": {
      "types": "./dist/index.d.ts",
      "default": "./dist/EasySpeech.js"
    }
  }
},
```

**Comment by jankapunkt** [comment]
Please try `easy-speech@2.4.0-rc.0` and let me know if things work as expected

**Comment by annam002** [comment]
Ran into the same problem. Upgrading the version fixed it for me.

**Comment by jankapunkt** [comment]
@annam002 thanks for the feedback. I will release 2.4.0 this week, since there were no complaints on the rc so far. @enyo please let me know if there are still issues with types in the RC

**Comment by enyo** [comment]
@jankapunkt yes that worked. Thanks!
