### ISSUE TITLE
Speak doesn't play again in window chrome after pausing it.

### ISSUE THREAD

**Issue by abhishekkumar023** [leaonline/easy-speech#300]
[x] I have read the [FAQ section](https://github.com/jankapunkt/easy-speech/blob/master/FAQ.md) and have checked
    that none of it describe the issue I'm about to report.

**Describe the bug**
I played it and paused it. After leaving it for 10 seconds, when I again want to resume it, it didn't work / speak.

**To Reproduce**
1. Go to Chrome browser in window OS
2. Click on Button which trigger EasySpeech.speak()
3. It will start speaking with no issues. Now, Pause it in the middle.
4. go to different tab and / or wait for 10 seconds, now again click the button to play it, notice, it didn't speak again.
5. It only happens in chrome browser in window.

**Expected behavior**
It should again play even after waiting for 10-20 seconds or moving out to new tab after pausing and coming back to play it

**Desktop (please complete the following information):**
 - OS: Window
 - Browser Chrome
 - Version : 126.0.6478.183 and 126.0.6478.127

**Comment by jankapunkt** [comment]
Hi @abhishekkumar023 thank you for reporting!

> now again click the button to play it, notice, it didn't speak again.

Does that mean it never plays again until you reload the page or does that mean it will not finish the paused speech but starts again from the first words?

**Comment by abhishekkumar023** [comment]
Hi 
It never plays again until we reload the page.
