### ISSUE TITLE
Quickly Calling play and pause one after another sets the voice to play in Windows Chrome

### ISSUE THREAD

**Issue by abhishekkumar023** [leaonline/easy-speech#301]
[x] I have read the [FAQ section](https://github.com/jankapunkt/easy-speech/blob/master/FAQ.md) and have checked
    that none of it describe the issue I'm about to report.

**Describe the bug**
I have a single button which will trigger play when we click it for first time, when we click it second time, it will pause it, when we click it third time, it will resume. When I double click this button, it still plays but doesn't stop again even after clicking the button again.

**To Reproduce**
1. Go to Windows -  chrome browser
2. Double Click on button to call EasySpeech.play() and EasySpeech.pause() one after another.
3. Notice - it is still playing and doesn't stop again, even after clicking that button again. 
4. The button state has been changed though. So, for playing the button icon is different for pause - it's different. It's successfully changed to pause but it's still playing the sound

**Expected behavior**
It should stop playing

**Desktop (please complete the following information):**
 - OS: Window
 - Browser : Chrome
 - Version : 126.0.6478.127  and 126.0.6478.183

**Comment by jankapunkt** [comment]
Hi @abhishekkumar023 thanks for reporting this, too! How would this be solved in EasySpeech? I think this should rather be solved on the button/ui level by either preventing the double click even (preventDefault + stopPropagation) or by using something like throttle or debounce.
